packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - puppeteer

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - prisma
  - sharp
  - unrs-resolver
